name: alice
description: Alice is an HTTP Inspector tool which helps debugging http requests. It catches and stores http requests and responses, which can be viewed via simple UI.
version: 0.4.2
#author: Jakub Homlala <jhomlala@gmail.com>
homepage: https://github.com/jhomlala/alice

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.0.0
  dio: ^5.4.3+1
  flutter_local_notifications: ^17.1.2
  rxdart: ^0.27.7
  path_provider: ^2.1.3
  permission_handler: ^11.0.1
  package_info_plus: ^6.0.0
  open_filex: ^4.3.2
  sensors_plus: ^5.0.1
  share_plus: ^9.0.0
  chopper: ^8.0.0
  collection: ^1.17.1
  url_launcher: ^6.2.6

dev_dependencies:
  very_good_analysis: ^5.1.0
