name: alice
description: Alice is an HTTP Inspector tool which helps debugging http requests. It catches and stores http requests and responses, which can be viewed via simple UI.
version: 0.1.5
author: Jakub Homlala <jhomlala@gmail.com>
homepage: https://github.com/jhomlala/alice

environment:
  sdk: ">=2.6.0 <3.0.0"
  flutter: ">=1.12.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+4
  dio: ^3.0.9
  flutter_local_notifications: ^1.4.4+4
  rxdart: ^0.24.0

  path_provider: ^1.6.5
  permission_handler: ^5.0.0+hotfix.3
  package_info: ^0.4.0+16
  open_file: ^3.0.1
  shake: ^0.1.0
  share: ^0.6.3+6
  chopper: ^3.0.2
  better_player: ^0.0.22

#Dummy classes
flutter:
  plugin:
    platforms:
      android:
        package: com.jhomlala.alice
        pluginClass: Alice
      ios:
        pluginClass: Alice
