name: alice
description: Alice is an HTTP Inspector tool which helps debugging http requests. It catches and stores http requests and responses, which can be viewed via simple UI.
version: 0.3.3
#author: Jakub Homlala <jhomlala@gmail.com>
homepage: https://github.com/jhomlala/alice

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  dio: ^5.3.3
  flutter_local_notifications: ^16.1.0
  rxdart: ^0.27.7

  path_provider: ^2.1.1
  permission_handler: ^11.0.1
  package_info_plus: ^4.2.0
  open_filex: ^4.3.4
  sensors_plus: ^3.1.0
  share_plus: ^7.2.1
  chopper: ^7.0.9
  collection: ^1.17.2
  url_launcher: ^6.2.1

dev_dependencies:
  lint: ^2.1.2
