name: alice_lightweight
description: Lightweight Alice version. Removed additional dependencies except dio.
version: 1.0.0
homepage: https://github.com/jhomlala/alice

environment:
  sdk: ">=2.6.0 <3.0.0"
  flutter: ">=1.12.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.2
  dio: ^3.0.9
  rxdart: ^0.24.1
  share: ^0.6.4+3
