name: alice
description: Alice is an HTTP Inspector tool which helps debugging http requests. It catches and stores http requests and responses, which can be viewed via simple UI.
version: 0.1.6
author: Jakub Homlala <jhomlala@gmail.com>
homepage: https://github.com/jhomlala/alice

environment:
  sdk: ">=2.6.0 <3.0.0"
  flutter: ">=1.12.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.2
  dio: ^3.0.10
  flutter_local_notifications: ^3.0.1+7
  rxdart: ^0.24.1

  path_provider: ^1.6.24
  permission_handler: ^5.0.1+1
  package_info: ^0.4.3+2
  open_file: ^3.0.3
  shake: ^0.1.0
  share: ^0.6.5+4
  chopper: ^3.0.2
  better_player: ^0.0.36
