name: alice_chopper
description: "Alice + Chopper integration. It contains plugin for Alice which allows to use Chopper package."
version: 1.0.7
repository: https://github.com/jhomlala/alice
homepage: https://github.com/jhomlala/alice
topics:
  - http
  - inspector
  - alice
  - chopper
  - interceptor

environment:
  sdk: '>=3.4.1 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  alice: ^1.0.0-dev.12
  chopper: ^8.0.0
  http: ^1.2.1
  uuid: ^4.4.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^4.0.0
  test: ^1.25.2
  alice_test: ^1.0.0
  mocktail: ^1.0.4
  build_runner: ^2.4.9
  chopper_generator: ^8.0.0
  json_serializable: ^6.8.0
  json_annotation: ^4.9.0
  equatable: ^2.0.5
