name: example
description: "A project to showcase http and Alice integration."
publish_to: 'none'

version: 1.0.0+3

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  alice:
  alice_http:
  http: ^1.4.0

dev_dependencies:
  flutter_lints: ^5.0.0

dependency_overrides:
  alice:
    path: ../../packages/alice
  alice_http:
    path: ../../packages/alice_http

flutter:
  uses-material-design: true
