name: alice_dio
description: "Alice + Dio integration. It contains plugin for Alice which allows to use Dio package."
version: 1.0.6
repository: https://github.com/jhomlala/alice
homepage: https://github.com/jhomlala/alice
topics:
  - http
  - inspector
  - dio
  - interceptor
  - alice

environment:
  sdk: '>=3.4.1 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  alice: ^1.0.0-dev.12
  dio: ^5.4.3+1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^4.0.0
  test: ^1.25.2
  mocktail: ^1.0.4
  http_mock_adapter: ^0.6.1
  alice_test: ^1.0.0