name: alice_chopper_example
description: "Alice + Chopper Example"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+3

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  alice:
  alice_chopper:
  chopper: ^8.2.0
  json_annotation: ^4.9.0
  equatable: ^2.0.7

dev_dependencies:
  build_runner: ^2.5.4
  chopper_generator: ^8.2.0
  json_serializable: ^6.9.5
  flutter_lints: ^5.0.0
  lints: ^5.1.1

dependency_overrides:
  alice:
    path: ../../packages/alice
  alice_chopper:
    path: ../../packages/alice_chopper

flutter:
  uses-material-design: true
