name: alice_http_client_example
description: "A project to showcase http client and Alice integration."
publish_to: 'none'

version: 1.0.0+3

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  alice:
  alice_http_client:

dev_dependencies:
  flutter_lints: ^5.0.0

dependency_overrides:
  alice:
    path: ../../packages/alice
  alice_http_client:
    path: ../../packages/alice_http_client

flutter:
  uses-material-design: true
