name: alice_objectbox_example
description: "Alice + ObjectBox + HTTP package - Example"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+2

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  alice:
  alice_http:
  alice_objectbox:
  cupertino_icons: ^1.0.8
  http: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

dependency_overrides:
  alice:
    path: ../../packages/alice
  alice_http:
    path: ../../packages/alice_http
  alice_objectbox:
    path: ../../packages/alice_objectbox

flutter:
  uses-material-design: true
