name: alice_objectbox
description: "Alice + ObjectBox integration. It contains a plugin for Alice which stores http requests and responses in an ObjectBox NoSQL database."
version: 1.0.5
repository: https://github.com/jhomlala/alice
homepage: https://github.com/jhomlala/alice
topics:
  - http
  - inspector
  - alice
  - interceptor
  - objectbox

environment:
  sdk: ">=3.7.0 <4.0.0"
  flutter: ">=3.29.0"

dependencies:
  flutter:
    sdk: flutter
  alice: ^1.0.0
  json_annotation: ^4.9.0
  meta: ^1.16.0
  objectbox: ^4.3.0
  objectbox_flutter_libs: ^4.3.0
  path: ^1.9.1
  path_provider: ^2.1.5
  flat_buffers: ^23.5.26

dev_dependencies:
  build_runner: ^2.4.1
  flutter_lints: ^5.0.0
  json_serializable: ^6.9.5
  objectbox_generator: ^4.3.0
