name: alice
description: Alice is an HTTP Inspector tool which helps debugging http requests. It catches and stores http requests and responses, which can be viewed via simple UI.
version: 1.0.0
homepage: https://github.com/jhomlala/alice
repository: https://github.com/jhomlala/alice
topics:
  - http
  - inspector
  - dio
  - chopper
  - interceptor

environment:
  sdk: ">=3.7.0 <4.0.0"
  flutter: ">=3.29.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^19.4.0
  rxdart: ^0.28.0
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  package_info_plus: ^8.3.0
  open_filex: ^4.6.0
  sensors_plus: ^6.1.1
  share_plus: ^11.0.0
  collection: ^1.19.1
  url_launcher: ^6.3.2
  equatable: ^2.0.7

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  lints: ^5.1.1
  test: ^1.25.15
  mocktail: ^1.0.4