name: alice
description: Alice is an HTTP Inspector tool which helps debugging http requests. It catches and stores http requests and responses, which can be viewed via simple UI.
version: 1.0.0-dev.12
homepage: https://github.com/jhomlala/alice
repository: https://github.com/jhomlala/alice
topics:
  - http
  - inspector
  - dio
  - chopper
  - interceptor

environment:
  sdk: ^3.0.0
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^17.2.3
  rxdart: ^0.28.0
  path_provider: ^2.1.4
  permission_handler: ^11.3.1
  package_info_plus: ^8.0.0
  open_filex: ^4.5.0
  sensors_plus: ^6.0.1
  share_plus: ^10.0.2
  collection: ^1.18.0
  url_launcher: ^6.3.0
  equatable: ^2.0.5

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  lints: ^4.0.0
  test: ^1.25.2
  mocktail: ^1.0.4