name: alice_http
description: "Alice + HTTP integration. It contains plugin for Alice which allows to use http package."
version: 1.0.6
repository: https://github.com/jhomlala/alice
homepage: https://github.com/jhomlala/alice
topics:
  - http
  - inspector
  - alice
  - interceptor

environment:
  sdk: '>=3.4.1 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  alice: ^1.0.0-dev.12
  http: ^1.2.1

dev_dependencies:
  flutter_lints: ^4.0.0