name: alice_http
description: "Alice + HTTP integration. It contains plugin for Alice which allows to use http package."
version: 1.0.7
repository: https://github.com/jhomlala/alice
homepage: https://github.com/jhomlala/alice
topics:
  - http
  - inspector
  - alice
  - interceptor

environment:
  sdk: ">=3.7.0 <4.0.0"
  flutter: ">=3.29.0"

dependencies:
  alice: ^1.0.0
  http: ^1.4.0

dev_dependencies:
  flutter_lints: ^5.0.0